export type ProcessId = 'wafer'|'oxidation'|'lithography'|'etch'|'deposition'|'metallization'|'eds'|'packaging';

export interface ProcessProfile {
  id: ProcessId; name: string; equipment: string; baseYield: number;
  objectives: string[]; overview: string[]; principles: string[];
  components: {name:string; role:string; zone:string}[];
  faults: {id:string; name:string; cause:string; symptom:string; defect:string; recovery:string; yieldLoss:number}[];
}

export const processProfiles: Record<ProcessId, ProcessProfile> = {
  wafer:{id:'wafer',name:'웨이퍼 제조',equipment:'CZ Crystal Puller',baseYield:96.8,
    objectives:['CZ 단결정 성장의 열수지와 직경 제어 이해','Pull rate·회전수·온도 변화가 결정 결함에 미치는 영향 분석','Neck–Shoulder–Body–Tail 운전과 안전 인터록 수행'],
    overview:['원료 다결정 Si 장입 및 진공/Ar 치환','1420°C 이상 용융과 Seed 결정 접촉','Dash necking으로 전위 제거','Shoulder 확대 후 300 mm Body 직경 제어','Tail 형성·냉각·Ingot slicing/CMP'],
    principles:['Heat balance와 meniscus 형상이 결정 직경을 결정','Seed와 crucible 역회전으로 온도·도펀트 균일도 확보','Pull rate가 빠르면 직경 감소와 thermal stress 증가'],
    components:[{name:'Quartz Crucible',role:'고순도 Si 용융액을 담고 균일하게 회전',zone:'CHAMBER'},{name:'Graphite Heater',role:'Si 융점 이상 열원과 온도 분포 형성',zone:'POWER'},{name:'Seed Chuck',role:'결정방향 Seed 고정 및 인상·회전',zone:'DRIVE'},{name:'Diameter Camera',role:'Meniscus 밝기와 직경을 실시간 계측',zone:'VISION'},{name:'Ar Gas / Vacuum',role:'산화 방지와 불순물 배출',zone:'UTILITY'}],
    faults:[{id:'temp-high',name:'용융온도 과승',cause:'Heater PID/TC 오설정',symptom:'직경 감소·meniscus 불안정',defect:'Slip·dislocation',recovery:'Heater 출력 저감 후 안정화',yieldLoss:12},{id:'pull-fast',name:'Pull rate 과다',cause:'레시피 단위 입력 오류',symptom:'직경 축소·열응력 증가',defect:'직경불량·crystal crack',recovery:'인상속도 감속 및 shoulder 재형성',yieldLoss:18}]},
  oxidation:{id:'oxidation',name:'산화공정',equipment:'Horizontal Oxidation Furnace',baseYield:98.2,
    objectives:['Deal–Grove 성장 모델과 Dry/Wet 차이 이해','온도·시간·가스유량으로 목표 두께 제어','Furnace boat·quartz tube·MFC 인터록 운전'],
    overview:['Wafer RCA clean·Boat 적재','Tube purge와 온도 안정화','Dry O₂ 또는 Wet steam 공급','계면 반응과 산화막 확산 성장','N₂ purge·cooling·ellipsometry'],
    principles:['초기 산화는 계면반응 지배, 두꺼운 막은 확산 지배','Wet oxidation은 빠르고 Dry oxidation은 치밀·전기특성 우수','온도 편차는 wafer-to-wafer 두께 편차로 연결'],
    components:[{name:'Quartz Process Tube',role:'고온 반응 공간과 오염 격리',zone:'CHAMBER'},{name:'Resistance Heater Zones',role:'입구·중앙·출구 온도 균일화',zone:'HEAT'},{name:'Mass Flow Controller',role:'O₂/N₂/H₂O 유량 정밀 제어',zone:'GAS'},{name:'Wafer Boat',role:'웨이퍼 간격과 가스 흐름 유지',zone:'TRANSFER'},{name:'Bubbler/Steam Generator',role:'Wet oxidation 수증기 생성',zone:'UTILITY'}],
    faults:[{id:'mfc-drift',name:'O₂ MFC Drift',cause:'MFC 영점/Span 불량',symptom:'성장속도 편차',defect:'막두께 불균일',recovery:'Gas 차단·MFC calibration',yieldLoss:9},{id:'temp-low',name:'Zone 온도 저하',cause:'Heater/TC 단선',symptom:'Boat 위치별 막두께 차이',defect:'Vth 분포 확대',recovery:'공정 중지·Zone heater 점검',yieldLoss:15}]},
  lithography:{id:'lithography',name:'포토공정',equipment:'ArF Stepper / Scanner',baseYield:97.5,
    objectives:['Coat–Align–Expose–Develop 전 과정 이해','Dose·Focus·NA가 CD와 DOF에 미치는 영향 분석','Overlay 및 particle 불량 대응'],overview:['HMDS prime·PR dispense','Spin coat·soft bake','Reticle load·wafer alignment','Focus leveling·scan exposure','PEB·develop·CD/overlay 검사'],principles:['Rayleigh 식 CD=k₁λ/NA, DOF=k₂λ/NA²','Dose 부족은 미현상, 과다는 CD bias 유발','Stage alignment와 lens aberration이 overlay를 지배'],components:[{name:'Illumination Source',role:'193 nm ArF 노광 에너지 생성',zone:'OPTICS'},{name:'Reticle Stage',role:'마스크 패턴 고속 동기 주사',zone:'STAGE'},{name:'Projection Lens',role:'패턴 축소 투영과 초점 형성',zone:'OPTICS'},{name:'Wafer Stage',role:'진공 고정·정밀 XYθ 이동',zone:'STAGE'},{name:'Alignment Sensor',role:'마크 인식과 overlay 보정',zone:'VISION'}],faults:[{id:'dose-low',name:'노광량 부족',cause:'Lamp decay/recipe 오류',symptom:'PR 잔사·CD 증가',defect:'Pattern open',recovery:'Dose monitor 확인·재교정',yieldLoss:14},{id:'focus',name:'Focus offset',cause:'Level sensor 오염',symptom:'패턴 흐림·CD 분산',defect:'Bridge/line collapse',recovery:'센서 청소·focus map 재측정',yieldLoss:17}]},
  etch:{id:'etch',name:'식각공정',equipment:'ICP-RIE Plasma Etcher',baseYield:96.9,objectives:['플라즈마 생성과 ion-assisted etch 이해','RF·압력·가스비로 selectivity/anisotropy 제어','Endpoint와 chamber fault 대응'],overview:['Load-lock pump down','Wafer clamp·He backside cooling','Process gas stabilization','ICP source/RF bias ignition','Endpoint 검출','Purge·vent·post clean'],principles:['Source power는 radical 밀도, bias power는 ion energy를 결정','저압은 방향성, 고압은 측면 반응 증가','가스 화학과 polymer balance가 selectivity/sidewall 결정'],components:[{name:'ICP Coil',role:'고밀도 plasma 생성',zone:'POWER'},{name:'RF Bias Electrode',role:'Ion 수직 가속과 anisotropy 제어',zone:'POWER'},{name:'Showerhead / MFC',role:'공정가스 균일 분배',zone:'GAS'},{name:'ESC Chuck',role:'Wafer 고정·온도 제어',zone:'CHAMBER'},{name:'OES Endpoint',role:'방출광 변화로 막 종료점 검출',zone:'SENSOR'}],faults:[{id:'pressure-high',name:'Chamber pressure 과다',cause:'Throttle valve/MFC 오류',symptom:'Ion 산란·undercut 증가',defect:'CD loss·sidewall bowing',recovery:'RF off·gas close·APC 점검',yieldLoss:16},{id:'endpoint',name:'Endpoint miss',cause:'OES window 오염',symptom:'Over-etch 지속',defect:'기저막 손상',recovery:'공정 중단·window clean',yieldLoss:13}]},
  deposition:{id:'deposition',name:'증착·이온주입',equipment:'PVD/CVD Cluster & Ion Implanter',baseYield:96.4,objectives:['PVD/CVD 막 성장과 implant 분포 이해','전력·압력·유량·energy/dose 최적화','진공·가스·고전압 인터록 대응'],overview:['Load-lock vacuum','Pre-clean/degas','PVD/CVD film deposition','막두께·균일도 측정','Implant energy/dose scan','Anneal·SIMS/4PP 검사'],principles:['증착률과 step coverage는 mean free path·surface reaction에 의존','Implant energy는 Rp, dose는 농도 적분값 결정','Anneal은 결정손상 회복과 dopant activation 수행'],components:[{name:'Load Lock',role:'대기와 고진공 격리',zone:'VACUUM'},{name:'Target/Showerhead',role:'금속 원자 또는 precursor 공급',zone:'SOURCE'},{name:'RF/DC Power',role:'Plasma·sputter energy 생성',zone:'POWER'},{name:'Ion Source/Analyzer',role:'Ion 생성·질량선별·가속',zone:'IMPLANT'},{name:'Wafer Scanner',role:'Beam dose 균일 분포',zone:'STAGE'}],faults:[{id:'vacuum',name:'Base vacuum 불량',cause:'Seal leak/pump 성능저하',symptom:'산소·수분 증가',defect:'막저항 증가·particle',recovery:'Leak check·pump regeneration',yieldLoss:15},{id:'dose',name:'Implant dose 과다',cause:'Beam current calibration 오류',symptom:'Sheet R 저하·junction shift',defect:'Leakage 증가',recovery:'Beam off·Faraday calibration',yieldLoss:20}]},
  metallization:{id:'metallization',name:'금속배선',equipment:'Cu Plating & CMP Cluster',baseYield:95.8,objectives:['Dual damascene 구조와 Barrier/Seed 역할 이해','Electroplating·CMP 변수와 resistance 분석','Void·open·short·dishing 대응'],overview:['Via/trench pre-clean','Barrier/Seed PVD','Cu electroplating','Anneal grain growth','CMP overburden 제거','Kelvin/open-short 검사'],principles:['Barrier는 Cu diffusion, Seed는 도금 전류 경로를 제어','Bottom-up fill은 accelerator/suppressor balance로 형성','R=ρL/A 및 electromigration가 배선 신뢰성 지배'],components:[{name:'Barrier/Seed Chamber',role:'Ta/TaN과 연속 Cu seed 형성',zone:'PVD'},{name:'Plating Cell',role:'전기화학적 Cu bottom-up fill',zone:'WET'},{name:'Chemical Dosing',role:'첨가제 농도와 bath chemistry 유지',zone:'CHEM'},{name:'CMP Head/Platen',role:'압력·회전으로 overburden 제거',zone:'CMP'},{name:'4PP/Kelvin Tester',role:'Sheet·line resistance 측정',zone:'METROLOGY'}],faults:[{id:'seed-open',name:'Seed 불연속',cause:'High aspect via coverage 부족',symptom:'도금 nucleation 실패',defect:'Via void/open',recovery:'Seed 재증착·preclean 확인',yieldLoss:22},{id:'cmp-over',name:'CMP 과연마',cause:'Endpoint/pressure 오류',symptom:'Cu recess·dishing',defect:'저항 증가·line open',recovery:'Head pressure·endpoint 보정',yieldLoss:18}]},
  eds:{id:'eds',name:'EDS',equipment:'Automatic Wafer Prober & ATE',baseYield:94.5,objectives:['Probe contact·parametric·functional test 이해','Bin map과 yield 산출 및 spatial pattern 분석','Contact/temperature/ESD trouble 대응'],overview:['Wafer ID·notch alignment','Chuck temperature stabilization','Probe card contact','DC parametric test','Functional/timing test·binning','Wafer map·yield report'],principles:['Yield=Good dies/Total tested dies×100','Contact resistance와 leakage가 false fail을 유발','Wafer map 공간 패턴은 전공정 이상 위치를 추적'],components:[{name:'Probe Card',role:'Die pad에 전기적 접촉',zone:'CONTACT'},{name:'Precision Chuck',role:'Wafer 온도·평탄·좌표 유지',zone:'STAGE'},{name:'Tester Pin Electronics',role:'전원·신호 인가 및 응답 비교',zone:'ATE'},{name:'Vision Alignment',role:'Pad와 needle 위치 자동 보정',zone:'VISION'},{name:'Wafer Map Server',role:'Bin·좌표·수율 데이터 관리',zone:'DATA'}],faults:[{id:'contact',name:'Probe contact 불량',cause:'Needle 오염/overdrive 부족',symptom:'연속 fail cluster',defect:'False reject',recovery:'Needle clean·contact check',yieldLoss:11},{id:'esd',name:'ESD event',cause:'Grounding/ionizer 이상',symptom:'Leakage 급증',defect:'Gate oxide damage',recovery:'Test 중지·ESD audit',yieldLoss:25}]},
  packaging:{id:'packaging',name:'패키징',equipment:'Die/Wire Bonder & Mold Cell',baseYield:97.1,objectives:['Die attach·wire bond·mold·final inspection 이해','Force·time·temperature와 접합강도 관계 분석','Delamination·wire sweep·void 대응'],overview:['Wafer saw·die pick','Die attach·cure','Wire/flip-chip bonding','Molding·post mold cure','Trim/form·mark','X-ray·SAT·pull/shear test'],principles:['Bond force·ultrasonic energy·temperature가 intermetallic 접합 결정','CTE mismatch와 moisture가 delamination/stress 유발','Thermal resistance는 junction temperature와 수명 지배'],components:[{name:'Die Bonder Vision',role:'Die 방향·좌표 인식과 정렬',zone:'VISION'},{name:'Bond Head/Collet',role:'Die pick·place와 하중 인가',zone:'MOTION'},{name:'Wire Bond Capillary',role:'Ball/stitch bond 형성',zone:'BOND'},{name:'Mold Press',role:'EMC 충진과 package 형상 형성',zone:'MOLD'},{name:'X-ray/SAT',role:'내부 void·delamination 비파괴 검사',zone:'INSPECTION'}],faults:[{id:'bond-low',name:'Bond force 부족',cause:'Force calibration/recipe 오류',symptom:'Pull strength 저하',defect:'Wire lift/open',recovery:'Bond head calibration·rework 판정',yieldLoss:14},{id:'mold-void',name:'Mold void',cause:'Vacuum/transfer pressure 부족',symptom:'X-ray void·수분 경로',defect:'Crack/delamination',recovery:'Mold vacuum·compound 조건 점검',yieldLoss:12}]}
};
